# Generated by Django 2.2.1 on 2019-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
